examples/main.go
optimizely/client/client.go
optimizely/client/client_test.go

- Introduces a top-level defer guard to ensure we recover from any panicking when using the IsFeatureEnabled API
- Unit tests

feat(err): Panic handling in the IsFeatureEnabled API.

---

optimizely/decision/evaluator/condition.go
optimizely/decision/evaluator/matchers/substring.go
optimizely/decision/evaluator/matchers/substring_test.go

- Enables `substring` as a condition match type in `condition.go`
- Adds substring matcher functionality in `substring.go`
- Unit tests in `substring_test.go`
[OASIS-4941](https://optimizely.atlassian.net/browse/OASIS-4941)

feat(decision): Add Substring Matcher 

---

optimizely/decision/evaluator/matchers/substring.go
optimizely/decision/evaluator/matchers/substring_test.go

- Fixed the substring matching logic by switching `stringValue` and `attributeValue`
- Modified unit tests in `substring_test.go`
[OASIS-5200](https://optimizely.atlassian.net/browse/OASIS-5200)

fix(decision): substring matcher reversal

---

optimizely/client/factory.go
optimizely/config/polling_manager.go
optimizely/config/polling_manager_test.go
optimizely/config/requester.go
optimizely/config/requester_test.go

- Allows creation of polling config manager with defaults instead of having to always pass in a requester object
- Unit tests

refac(config-manager): simplifies the creation of polling config manager with options

---

optimizely/client/factory.go
optimizely/decision/entities.go

- Added DecisionService as an option to OptimizelyClient custom configuration.
- Fixed casing for Source Rollout.

fix(testapp-support): Fixes to allow test-app to use notification listeners.

---

examples/main.go
optimizely/client/client.go
optimizely/client/factory.go
optimizely/config/datafileprojectconfig/config.go
optimizely/config/datafileprojectconfig/mappers/feature.go
optimizely/config/datafileprojectconfig/mappers/feature_test.go
optimizely/decision/composite_feature_service.go
optimizely/decision/entities.go
optimizely/event/dispatcher.go
optimizely/event/factory_test.go
optimizely/event/processor.go
optimizely/event/processor_test.go

This PR enables sending impressions for features tests from the `IsFeatureEnabled` API: 
- Adds experiments to the feature model in the project config
- Re-enabled the experiment decision service in the composite feature service to evaluate feature tests
- Integrate the event processor with the Optimizely client and send event to it from the IsFeatureEnabled API
- Unit

feat: Hook up event processor to IsFeatureEnabled.

---

optimizely/client/factory.go
optimizely/event/factory_test.go
optimizely/event/processor.go
optimizely/event/processor_test.go

- Passes the cancelable context from the client down to the event processor
- Unit

feat(event): Use the cancelable context in the event processor.

---

.travis.yml
optimizely/client/client.go
optimizely/client/client_test.go
optimizely/config/polling_manager.go
optimizely/config/polling_manager_test.go
optimizely/config/static_manager.go
optimizely/config/static_manager_test.go
optimizely/interface.go

- Update `ProjectConfigManager#GetConfig` also return err
- Update `ProjectConfigManager` implementations with the new signature
- Replace `isClientValid` with standard `GetProjectConfig`
- Slight refactor of the `MockProjectConfigManager` to be a bit more flexible
- Add tests to maintain coverage
When exposing ProjectConfig I felt that the use of `isValidClient` was better served with the "comma-err" idiom. So I replaced that initial check with a common method `GetProjectConfig` with is used internally and externally to get a project config.
Note: this replaces https://github.com/optimizely/go-sdk/pull/82

Replace isValidClient with GetProjectConfig.

---

optimizely/client/factory_test.go
optimizely/event/dispatcher.go
optimizely/event/processor.go
optimizely/event/processor_test.go

- Refactors the event dispatcher interface to return the success arg instead of taking a callback since the dispatchEvent method itself is a blocking operation

refac(event): Return success value instead of using callback in dispatcher interface

---

CHANGELOG.MD
README.md
optimizely/version.go

- Bumps the client version to 0.2.0
- Adds release notes for the new release 0.2.0

chore(release): Bump version and add release notes for 0.2.0.

---

optimizely/config/polling_manager.go

Introducing this method will allow some advanced use cases like requesting datafile be updated on demand.

Adjusting config manager to support a Sync method

---

optimizely/decision/bucketer/experiment_bucketer.go
optimizely/decision/bucketer/experiment_bucketer_test.go
optimizely/decision/composite_feature_service.go
optimizely/decision/composite_feature_service_test.go
optimizely/decision/helpers_test.go

This change introduces support for feature tests belonging to the same mutex group.
NOTE: The current change avoids refactoring a lot of the code as the ideal way to do this is to bucket into group to determine experiment and then bucket into experiment. 
For eg. let's say there are N experiments in a mutex group. In the current scenario we will bucket N times to evaluate feature tests, but we only need to bucket 2 times: once for group and once for experiment.
That will come as an enhancement to this code.

Introducing mutex support for feature tests

---

.travis.yml
optimizely/notification/manager.go
optimizely/notification/manager_test.go

1. Fixed implementation of golangci-lint as suggested in the documentation. The previously implemented way was only suggested for local installation and was flaky.
2. Made a minor fix as per linter recommendation.

fix(linter): Fixed golangci-lint implementations

---

optimizely/decision/composite_experiment_service.go
optimizely/decision/composite_experiment_service_test.go
optimizely/decision/composite_feature_service.go
optimizely/decision/composite_feature_service_test.go
optimizely/decision/composite_service.go
optimizely/decision/composite_service_test.go
optimizely/decision/experiment_bucketer_service.go
optimizely/decision/experiment_bucketer_service_test.go
optimizely/decision/feature_experiment_service.go
optimizely/decision/feature_experiment_service_test.go
optimizely/decision/helpers_test.go
optimizely/decision/rollout_service.go
optimizely/decision/rollout_service_test.go

- Moved the audience targeting logic into `ExperimentBucketerService` as it makes more sense to couple them.
- Refactored some of the tests to be organized around test `testify test suites` to simplify test setup
- `CompositeService` only has a `CompositeExperimentService` and a `CompositeFeatureService` instead of arrays for each type of decision service.
- Moved feature experiment logic from `CompositeFeatureService` into the `FeatureExperimentService` "class"
- Unit tests

refac(decision): moved various components around.

---

examples/benchmark/main.go
examples/main.go
go.mod
go.sum
optimizely/client/factory.go
optimizely/config/polling_manager.go
optimizely/config/polling_manager_test.go
optimizely/decision/composite_service.go
optimizely/decision/composite_service_test.go
optimizely/registry/service.go
optimizely/registry/service_test.go

- Refactors how we construct top-level components with the notification center
- This simplifies the initialization code for PollingConfigManager and DecisionService because now they don't need to know about the internal notification center
- Unit tests (missing) for the service registry

feat(registry): Added service registry for retrieving instances of notif center

---

optimizely/client/client.go
optimizely/client/client_test.go
optimizely/client/fixtures_test.go
optimizely/decision/composite_feature_service.go
optimizely/decision/composite_feature_service_test.go
optimizely/decision/composite_service.go
optimizely/decision/composite_service_test.go
optimizely/decision/feature_experiment_service.go
optimizely/decision/feature_experiment_service_test.go
optimizely/decision/interface.go
optimizely/notification/entities.go

- Add `Activate` API for A/B tests
- Add `GetVariation` API for A/B tests
- Introduced test suites and test fixtures for client package testing
- Adds Decision notifications for both
- Unit
Address #59

feat(activate): Add Activate and GetVariation APIs.

---

CHANGELOG.MD
optimizely/version.go

- Bumps to 1.0.0-beta2
- Adds changelog entry

chore: Prepare release 1.0.0-beta2.

---

optimizely/client/client_test.go
optimizely/client/fixtures_test.go
optimizely/entities/experiment.go

- Moves tests into a suite with reused setup steps to avoid code duplication
- Introduces helper test functions for creating entities

refac(test): Move some client tests into test suite.

---

examples/benchmark/main.go
examples/main.go
optimizely/client/client_test.go
optimizely/client/factory.go
optimizely/client/factory_test.go
optimizely/client/fixtures_test.go
optimizely/config/polling_manager.go
optimizely/config/polling_manager_test.go
optimizely/entities/experiment.go
optimizely/event/factory_test.go
optimizely/event/processor.go
optimizely/event/processor_test.go

- Aims to simplify the construction of the top level components by removing the executionContext from the required path
- Renames some of the option functions to the new paradigm where they are prepended with `With`
- Important caveat to note is that now we have to explicitly call the `Start` methods of the `PollingConfigManager` and `QueueingEventProcessor`
- Unit

refac(context): Refactor to make execution context optional for components

---

.travis.yml
optimizely/config/datafileprojectconfig/mappers/experiment.go
optimizely/decision/composite_experiment_service.go
optimizely/decision/composite_experiment_service_test.go
optimizely/decision/experiment_whitelist_service.go
optimizely/decision/experiment_whitelist_service_test.go
optimizely/decision/helpers_test.go
optimizely/decision/reasons/reason.go
optimizely/entities/experiment.go

Add `ExperimentWhitelistService`, which returns decisions based on the contents of `forcedVariations` in experiments in the datafile. `NewCompositeExperimentService` creates an `ExperimentWhitelistService` as its first child service, taking precedence over normal bucketing.
To support `ExperimentWhitelistService`, I added a `Whitelist` field to the `Experiment` entity. The value comes directly from `forcedVariations` of the datafile experiment. I named it `Whitelist` to match the term we use to talk about this kind of override, even though it's not named that in the datafile.
Added unit tests

feat: Add ExperimentWhitelistService

---

pkg/client/factory.go
pkg/client/factory_test.go
pkg/event/factory_test.go
pkg/event/processor.go
pkg/event/processor_test.go
tests/integration/support/client_wrapper.go

- Rename option func to be prepended with the word "With"
- Rename the QueueingEventProcessor to BatchEventProcessor to be more in line with our other SDKs and the dev docs

refac(ep): Rename options and EP implementation.

---

.travis.yml
pkg/client/client.go
pkg/client/client_test.go

This PR revises how the top-level client handles and returns errors:
- Only fatal errors are returned: invalid/no config and unhandled panics
- Other "errors" are logged as warning and will not necessarily return zero-value result

refac(client): Revise how the client handles and returns errors.

---

pkg/decision/composite_feature_service.go
pkg/decision/composite_feature_service_test.go
pkg/event/factory.go

- Fixed `GetDecision` method for CompositeFeatureService, it now returns the last decision made in case every decision-service returned an error.
- Fixed assignment of `Key` property for visitor attribute struct.

(fix): Fixed GetDecision for CompositeFeatureService and key for VisitorAttribute.

---

pkg/decision/experiment_whitelist_service.go
pkg/decision/experiment_whitelist_service_test.go
pkg/decision/helpers_test.go

Previously, `GetDecision` of `ExperimentWhitelistService` was incorrectly using variation key to look up variations in the `Variations` map of an `Experiment` struct, in which keys are variation IDs, not variation keys. 
With this fix, we iterate over variations to find the one with the desired key. To avoid needing to search all variations, we can add a map keyed by variation key as a follow up.

fix(ExperimentWhitelistService): Fix finding variation by key

---

pkg/config/datafileprojectconfig/entities/entities.go
pkg/config/datafileprojectconfig/mappers/condition_trees.go
pkg/config/datafileprojectconfig/mappers/condition_trees_test.go
pkg/config/datafileprojectconfig/mappers/experiment.go
pkg/config/datafileprojectconfig/mappers/experiment_test.go
pkg/decision/evaluator/matchers/exact.go
pkg/decision/evaluator/matchers/exact_test.go
pkg/decision/evaluator/matchers/gt.go
pkg/decision/evaluator/matchers/gt_test.go
pkg/decision/evaluator/matchers/lt.go
pkg/decision/evaluator/matchers/lt_test.go
pkg/decision/evaluator/matchers/substring.go
pkg/decision/evaluator/matchers/substring_test.go

- Fixes bug where `experiment.audienceIds` is not parsed into audience condition tree in the absence of `experiment.audienceConditions`
- Fixes bug where user attribute lookup returns error when attribute not found during condition matching, and thus results in the `not` condition being short-circuited to false

fix: support audience ids

---

pkg/client/client.go
pkg/client/client_test.go

* Check `nil` feature to prevent panic
* Use consistent variable name `decisionContext` to distinguish from `userContext`
After we made a distinction between fatal and non-fatal errors, we can no longer assume that the Feature exists as part of the `DecisionContext`. Now we must check.

Check nil to prevent panic.

---

pkg/decision/composite_experiment_service.go
pkg/decision/entities.go
pkg/decision/interface.go
pkg/decision/persisting_experiment_service.go
pkg/decision/persisting_experiment_service_test.go

- Introduces UserProfileService interface
- Introduces a PersistingExperimentService class that wraps over the ExperimentBucketerService and performs UPS lookup and save
- Integration into the `CompositeExperimentService` will be done in a follow-up PR

feat(decision): User profile service

---

pkg/config/polling_manager.go
pkg/config/static_manager.go

related to https://optimizely.atlassian.net/browse/OASIS-5597

fix: return right after datafile getter returns an error (don't parse garbage)

---

pkg/client/factory.go
pkg/client/factory_test.go
pkg/client/fixtures_test.go
pkg/decision/composite_experiment_service.go
pkg/decision/composite_experiment_service_test.go
pkg/decision/composite_service.go
pkg/decision/composite_service_test.go
pkg/decision/helpers_test.go
pkg/decision/persisting_experiment_service_test.go

- Introduces options for User profile service and Experiment overrides store
- Unit (pending)

feat(client): Allow user profile service and overrides to be passed in.

---

pkg/client/factory_test.go
pkg/decision/composite_experiment_service_test.go
pkg/decision/experiment_override_service.go
pkg/decision/experiment_override_service_test.go

The built-in default implementation of `ExperimentOverrideStore` should be production ready, so it should be safe to use concurrently.
In this PR:
- The default implementation is renamed to `MapExperimentOverridesStore`
- A `sync.RWLock` is added to `MapExperimentOverridesStore`
- A `SetVariation` method is added for setting an override, which uses the mutex
- The `GetVariation` method is updated to use the mutex
- A new test is added that calls `GetVariation` and `SetVariation` concurrently from several goroutines

fix: Update built-in map-based ExperimentOverrideStore implementation to be concurrently usable

---

pkg/decision/experiment_override_service.go
pkg/decision/experiment_override_service_test.go

This adds a new function `NewMapExperimentOverridesStore`, so that `MapExperimentOverridesStore` can be used outside the `decision` package. Unit tests are updated to exercise `NewMapExperimentOverridesStore`.

fix: Add a public function to create a MapExperimentOverridesStore instance

---

pkg/decision/experiment_override_service.go
pkg/decision/experiment_override_service_test.go

This adds a `RemoveVariation` method of `MapExperimentOverridesStore`, which can be used to delete a previously set variation.

feat: Method for removing forced variations

---

pkg/decision/evaluator/matchers/exists.go
pkg/entities/user_context.go
pkg/entities/user_context_test.go

- Fixed evaluation code for `exists` condition.

fix(exists-condition) Fixed exists comparison for leaf condition.

---

pkg/client/client.go
pkg/decision/composite_experiment_service.go
pkg/decision/composite_experiment_service_test.go
pkg/decision/composite_feature_service.go
pkg/decision/experiment_bucketer_service.go
pkg/decision/feature_experiment_service.go
pkg/decision/persisting_experiment_service.go
pkg/decision/reasons/reason.go
pkg/decision/rollout_service.go
pkg/decision/rollout_service_test.go

- Fixes where and how we log various messages during the decision making process:
- 1. Gets rid of the `No decision made error` and instead returns the `decision` and `err` of the last decision maker
- 2. Logs debug messages in both feature experiment service as well as rollout service for clarity
- 3. Only logs (debug) bucketing ID if it is different from the user ID
- 4. Refactored the rollout_service_test to use suites
- Unit

fix(decision): Logs produced by the various decision services.

---

CHANGELOG.MD
pkg/version.go

- Releases master into the wild

chore: Prepare for 1.0.0-beta7 release.

---

.travis.yml
Makefile

- Adds makefile to simplify test commands
- Can move more things in here later on

chore(ci): Add makefile to simplify commands.

---

pkg/config/polling_manager.go
pkg/config/polling_manager_test.go
pkg/config/static_manager.go
pkg/event/dispatcher.go
pkg/utils/requester.go
pkg/utils/requester_test.go

1. Added support for caching datafiles using `Last-Modified`.

feat(PollingConfigManager): Implemented caching headers in PollingConfigManager.

---

pkg/event/processor_test.go

Speed up tests by not testing default timer which is 30 seconds.

(fix): remove sleep for 31 seconds. reduce time interval for testing

---

optimizely.go
pkg/client/client.go
pkg/client/factory.go
pkg/config/polling_manager.go
pkg/decision/composite_service.go
pkg/event/factory_test.go
pkg/event/processor.go
pkg/event/processor_test.go
pkg/interface.go

- Clean up public doc strings on client, factory and top-level components.
- Makes private some of the methods on the `BatchEventProcessor` which do not need to be public.

chore(docs): Clean up public doc strings on client, factory and top-level components.

---

pkg/client/client.go
pkg/config/polling_manager.go

Now it displays:
```
[Optimizely]2019/12/02 16:59:23 [Warning][Requester] error status code=403
[Optimizely]2019/12/02 16:59:23 [Warning][PollingConfigManager] unable to get fresh datafile
[Optimizely]2019/12/02 16:59:23 [Error][Client] received an error while computing experiment decision: unable to get fresh datafile, reason (http status code): 403 Forbidden
```

fix: correct error returned when SDK key is invalid

---

pkg/config/polling_manager.go

Now it returns this:
```
[Optimizely]2019/12/03 10:42:23 [Error][DatafileProjectConfig] Error parsing datafile.: readObjectStart: expect { or n, but found D, error found in #1 byte of ...|DATAFILE_JS|..., bigger context ...|DATAFILE_JSON_STRING_HERE|...
[Optimizely]2019/12/03 10:42:23 [Warning][PollingConfigManager] failed to create project config
[Optimizely]2019/12/03 10:42:23 [Error][Client] received an error while computing experiment decision: unable to parse datafile
```

fix: Invalid datafile JSON should return an error

---

pkg/client/factory.go
pkg/config/polling_manager.go
pkg/config/polling_manager_test.go

* Reverts signature changes for `PollingProjectConfigManager`
* Store `sdkKey` on the `PollingProjectConfigManager`
A recent PR https://github.com/optimizely/go-sdk/pull/195 broke backwards compatibility and added potential internal discrepancies of the current SDK. This change ensures that the SDK key used to initialize the Config Manager is used consistently throughout its lifecycle.

Revert signature changes to PollingProjectConfigManager.

---

pkg/client/factory_test.go
pkg/event/dispatcher.go
pkg/event/dispatcher_metrics.go
pkg/event/dispatcher_metrics_test.go
pkg/event/dispatcher_test.go
pkg/event/processor_test.go
scripts/coverage.sh
tests/integration/optlyplugins/proxy_dispatcher.go

* This provides the metrics on dispatcher queue that gets the LogEvent for dispatching. Metrics include primarily the size of the queue and the flush states: successful, failed, retried. 
* This PR is the initial work that needs to be done to support dispatcher metrics on sidedoor:
https://optimizely.atlassian.net/browse/OASIS-5667

feat: Add observability metrics for event queue

---

examples/main.go
go.mod
go.sum
pkg/client/client.go
pkg/client/client_test.go
pkg/client/factory.go
pkg/client/fixtures_test.go
pkg/config/interface.go
pkg/config/interface.go.go
pkg/config/polling_manager.go
pkg/config/static_manager.go
pkg/decision/entities.go
pkg/decision/helpers_test.go
pkg/event/factory.go
pkg/event/factory_test.go
pkg/event/version.go
tests/integration/optlyplugins/userprofileservice/utils.go
tests/integration/support/utils.go

- Moves the project config struct and project config manager interface from `pkg` into `config` so we don't have anything hanging off of the `pkg` package.
- Used Goland to to a refactor --> move
- Unit tests

refac(config): Move config interfaces back into config package

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/factory.go
pkg/client/factory_test.go
pkg/config/polling_manager.go
pkg/config/polling_manager_test.go
pkg/event/dispatcher.go
pkg/event/dispatcher_test.go
pkg/event/factory_test.go
pkg/event/processor.go
pkg/event/processor_test.go
pkg/utils/execgroup.go
pkg/utils/execgroup_test.go

* Allow `OptimizelyFactory` to accept a plain old **context** object (POCO)
* Rework `ExecutionCtx` into `ExecGroup` (ala `errgroup`)
* Refactor `Start` methods to *NOT* manage their own goroutines, but assume to be executed within one (this is similar to `http.ListenAndServe`)
This refactor started when I wanted to manage the `OptimizelyClient` lifecycle in my application, but was surprised that I couldn't easily just pass in my own cancellable context. Instead I had to implement my own `ExecutableCtx`, which also had concepts I didn't feel were immediately relevant to what I was trying to accomplish. Digging further I saw how the `ExecutableCtx` was being used it followed more of the semantics of an [errgroup](https://godoc.org/golang.org/x/sync/errgroup) which means simply managing a …

Refactor ExecutionCtx into ExecGroup.

---

pkg/client/client.go
pkg/client/client_test.go

Activate() returned vague runtime error (referencing null pointer).  After analysis and debugging, found 2 scenarios causing this:
- nil project config
- decision context is empty but variation is not nil somehow.
Added some protective logic against null references across client methods.

fix: logging nil project config, adding more meaningful error messages

---

pkg/notification/manager.go
pkg/notification/manager_test.go

- Fixed an issue when notification callbacks were calling Add/Remove of same notification manager. 
- All summary is in this PR. https://github.com/optimizely/go-sdk/pull/219
- Added unit tests for race detected scenarios.

fix(notification): race detected send notification issue

---

pkg/event/version.go

* Change `const` to `var` to allow being overridden.
A requirement of Optimizely Agent is to differentiate events originating from Agent vs the native go-sdk. Making these symbols variables allows the Agent build to set them during compile time via linker flags. Ex:
```
-X github.com/optimizely/go-sdk/pkg/event.ClientName=Agent
```

Allow ClientName and Version to be set at compile time.

---

pkg/config/optimizely_config.go

* Add JSON tags to OptimizelyConfig
Marshaling of the `OptimizelyConfig` into JSON was picking up the literal struct field names. This change uses JSON tags to map the struct fields to a more JSON friendlier representation.
```json
"ExperimentsMap": {
"sample_test": {
"ID": "10000",
"Key": "sample_test",
"VariationsMap": {
"sample_variation": {
"FeatureEnabled": true,
"ID": "20000",
"Key": "sample_variation",
"VariablesMap": {
"sample_variable": {
"ID": "30000",
"Key": "sample_variable",
"Type": "string",
"Value": "winning"
},
```
```json
"experimentsMap": {
"sample_test": {
"id": "10000",
"key": "sample_test",
"variationsMap": {
"sample_variation": {
"featureEnabled": true,
"id": "20000",
"key": "sample_variation",
"variablesMap": {
"sample_variable": {
"id": "30000",
"key": …
```

Add explicit JSON tags for OptimizelyConfig.

---

examples/main.go
pkg/config/polling_manager.go
pkg/config/polling_manager_test.go

Assigning error to a predefined error variable when CDN returns 403 response helps consumers such as sidedoor. Currently these consumers have to search the error message string for the text "403", which is not really convenient.

feat: set specific error from default project config manager when CDN returns 403 response

---

pkg/client/client_test.go
pkg/event/processor.go

OnEvent should be part of the event processor interface, and not only on BatchEventProcessor

feat: OnEvent should be part of the event processor interface

---

pkg/client/factory_test.go
pkg/config/datafileprojectconfig/config.go
pkg/config/datafileprojectconfig/config_test.go
pkg/config/polling_manager_test.go
pkg/config/static_manager_test.go

to be compatible with other sdk's, we are adding a check for a valid version of datafile.  go-sdk supports only version 4 of datafile, same as the family of more recent sdk's.

feat: add valid datafile version check

---

pkg/client/client.go
pkg/client/client_test.go

* Return typed variables to be more consistent with the discrete methods.
This change is also going to be consumed by Agent to be able to provide typed responses.

Return variables as an interface{} from GetAllFeatureVariables.

---

.travis.yml

- go 1.8 was unable to run unit tests because of `stretcher/testify` introduced new methods in the interface which we are not implementing. 
- checkedout specific branch which doesn't have that new method in the interface.  Here's the commit caused issue. 
https://github.com/stretchr/testify/commit/ea72eb91592e90d15a9e03ffe61f02493135d843
- All unit tests and FSC are running fine.

fix(1.8): go 1.8 fix

---

.travis.yml
pkg/event/processor.go
pkg/event/processor_test.go

- before dispatcher was initialized in go routine, which was wrong.
- now dispatcher is initialized in constructor, and just ticker starts in go routine.

fix:  instantiate event processor with dispatcher

---

CHANGELOG.MD
pkg/event/version.go

Release 1.1.1 with support for logging sdk key (masked by default) included in logs.  This is to handle the situation of multiple projects in one go-sdk instance.

chore (release): update changelog for release

---

pkg/logging/logger.go
pkg/logging/logger_test.go

* Fixes the logging field keys to be consumable
* Always include an "instance" field
* Optionally include the SDK key

fix(logger): Use exportable field names in log output.

---

CHANGELOG.MD

- refact: Update logging field keys to be consumable in structured logs [#246](https://github.com/optimizely/go-sdk/pull/246)

chore(release): Update CHANGELOG for 1.1.2 release

---

pkg/decision/helpers_test.go
pkg/decision/rollout_service.go
pkg/decision/rollout_service_test.go

Added support for multiple rollouts in `rollout_service`, this includes:
- Evaluating next available experiment if audience evaluation fails for previous.
- Falling back to the last experiment evaluation if bucketing fails for any of the experiments.

feature (multi-rollout): Added support for multiple rollouts.

---

pkg/decision/composite_service.go
pkg/decision/composite_service_test.go

- properly handling json variable in the notification listener

feat: added notification support for json variable

---

.travis.yml
pkg/optimizelyjson/optimizely_json.go
pkg/optimizelyjson/optimizely_json_test.go

- fixing a bug for getValue: when optimizleyJSON was built from a map, then getValue did not parse correctly with empty json_path

fix: fix getValue on optimizelyJson built from a map

---

CHANGELOG.MD
pkg/event/version.go

- Release 1.2.0 with support for Multi-rule rollout
- Will create a tag `v1.2.0` from `v.1.1.3` and cherry-pick #247 and the commit from this PR

chore: Prepare 1.2.0 release.

---

.travis.yml
docs/readme-sync/sdk-reference-guides/go-sdk/010 - install-sdk-go.md

@fscelliott i significantly improved our original PoC for readme-sync integration, now instead of triggering builds in external repos, i bring the readme-sync2 repo to the go-sdk build and run everything locally. ie. we are no longer dependant on the script/run_readme_sync.sh script (in readme-sync2) anymore, we can just get rid of that.
this change makes it a lot more robust since it has many fewer moving parts and it's actually faster because we end up cloning a lot less stuff.
one important thing to note is that this stage will only work if the docs/ directory (and the markdown files inside) are already existing in the repo so some other PR that adds these will need to be merged ahead of this PR.

add readme-sync integration

---

pkg/client/client.go
pkg/client/client_test.go
pkg/decision/entities.go

Temporary changes in go-sdk for adding a new method GetDetailedFeatureDecisionUnsafe
This is added to support some agent features. Which will be removed later on.
- All FSC should be passed.

feat: Added GetDetailedFeatureDecisionUnsafe

---

pkg/client/factory.go
pkg/client/factory_test.go
pkg/config/optimizely_config_test.go
pkg/config/polling_manager.go
pkg/config/polling_manager_test.go
pkg/config/static_manager.go
pkg/config/static_manager_test.go

- added support for authenticated datafiles
- refactored static config manager  to look more like polling config manager
- fixing a bug for polling interval set to 0 or below.
- here are different ways of initializing authenticated datafiles:
```
/************* default client  polling mgr ********************/
optimizelyClient, _ := optimizely.Client(sdkKey, client.WithDatafileAccessToken(token))
optimizelyClient.IsFeatureEnabled("EVENT_BATCHING", user)
/*********** custom polling mgr *****************/
pcm := config.NewPollingProjectConfigManager(sdkKey, config.WithDatafileAccessToken(token))
optimizelyClient, _ = optimizely.Client(sdkKey, client.WithConfigManager(pcm))
optimizelyClient.IsFeatureEnabled("EVENT_BATCHING", user)
/*************** custome polling mgr , setting polling …
```

feat: added authenticated datafile support

---

pkg/event/dispatcher_test.go
pkg/event/factory.go
pkg/event/processor.go
pkg/event/processor_test.go

- Made `eventEndpoint` public to be accessed by agent.
- FSC should pass.
- https://optimizely.atlassian.net/browse/OASIS-6455

feat(event-dispatcher): Exposing logx URL for agent.

---

pkg/client/factory.go
pkg/client/factory_test.go
pkg/config/optimizely_config_test.go
pkg/config/static_manager.go
pkg/config/static_manager_test.go

- bringing back old NewStaticProjectConfigManager that takes project config as a parameter
- renaming NewStaticProjectConfigManager to NewStaticProjectConfigManagerWithOptions
- changes are required for agent tests

feat: bring back old static manager constructor

---

pkg/registry/service.go
pkg/registry/service_test.go

- provide synchronization for Notification Center Cache
- this fix is for a case when many clients are initialized with different sdk keys ( Agent scenario)

fix: provide synchronization for Notification Center Cache

---

pkg/event/dispatcher.go
pkg/event/dispatcher_test.go

* Move sleep until after counters are updated.
* Increase sleep within the test to be less flaky.
@thomaszurkan-optimizely I noticed that within this test it says:
> // check the queue. bad event type should be removed.  but, not sent.
But the event is _not_ removed and we're asserting on a non-empty queue. Is this a bug or should the comment be updated?

Update test timing to fix flaky assertion.

---

.travis.yml

- go 1.10  testify was causing problem with the latest version. Added a download only flag to avoid this issue. 
- All stages must be passed.

ci: testify on go 1.10 causing problem

---

.travis.yml

Summary
-------
Stages run sequentially on Travis. If a stage fails, all the following stages are not executed. We execute source clear only on cron, and if due to any reason unit or integration tests fail, the source clear is not executed. Hence, moving source clear stage before tests. 
Test plan
---------
All unit tests must be passed. 
FSC must be passed.

ci: Run source clear only on cron and  before linting and tests

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/fixtures_test.go
pkg/config/datafileprojectconfig/config.go
pkg/config/datafileprojectconfig/entities/entities.go
pkg/config/interface.go
pkg/decision/entities.go
pkg/event/events.go
pkg/event/factory.go
pkg/event/factory_test.go

* Add experiment/feature flag key, variation key and type to impression events.
* Send events for **ALL** decision types.
* Add `Metadata` field to EventBatch.Decisions to capture flag type, key and variation key.
This change outline the proposed logical and structural changes required to support capturing all decision instances. The new eventbatch field is backwards compatible with the current pipeline.

Add support for sending flag decisions along with decision metadata.

---

pkg/decision/rollout_service.go
pkg/decision/rollout_service_test.go

- corrected logic for rollout services: don't populate experiment when variation is null 
- that should be safe and won't break notification center since 
```
if featureDecision.Source == FeatureTest {
sourceInfo["experimentKey"] = featureDecision.Experiment.Key
sourceInfo["variationKey"] = featureDecision.Variation.Key
}
```
is the only logic accessing  featureDecision.Experiment directly. And our change is happening on the rollout only

fix: corrected logic for rollout services

---

pkg/client/client.go
pkg/event/events.go
pkg/event/factory.go
pkg/event/factory_test.go

- added "enabled" field to decision metadata structure
- setting "enabled" to true for activate() since we check for non nil variation.

feat: added "enabled" field to decision metadata structure

---

.golangci.yml
.travis.yml
optimizely.go
pkg/decision/bucketer/experiment_bucketer_test.go
pkg/decision/bucketer/murmurhashbucketer.go
pkg/logging/level_log_consumer.go
pkg/notification/manager.go
pkg/utils/execgroup.go
pkg/utils/requester_test.go

- Fix and enforce Go formatting according to the integrated Go tool without simplify.
- All unit tests and new lint fmt test must pass.

Enforce go fmt in CI (errors are present).

---

pkg/config/datafileprojectconfig/config.go
pkg/config/datafileprojectconfig/config_test.go
pkg/config/datafileprojectconfig/mappers/attribute.go
pkg/config/datafileprojectconfig/mappers/attribute_test.go
pkg/config/datafileprojectconfig/mappers/audience.go
pkg/config/datafileprojectconfig/mappers/audience_test.go
pkg/config/datafileprojectconfig/mappers/condition_trees.go
pkg/config/datafileprojectconfig/mappers/events.go
pkg/config/datafileprojectconfig/mappers/events_test.go
pkg/config/datafileprojectconfig/mappers/experiment.go
pkg/config/datafileprojectconfig/mappers/experiment_test.go
pkg/config/datafileprojectconfig/mappers/feature.go
pkg/config/datafileprojectconfig/mappers/feature_test.go
pkg/config/datafileprojectconfig/mappers/rollout.go
pkg/config/datafileprojectconfig/mappers/rollout_test.go
pkg/config/interface.go
pkg/config/optimizely_config.go
pkg/config/optimizely_config_test.go
pkg/config/static_manager_test.go
pkg/config/testdata/optimizely_config_datafile.json
pkg/config/testdata/optimizely_config_expected.json
pkg/config/testdata/similar_exp_keys_datafile.json
pkg/config/testdata/similar_exp_keys_expected.json
pkg/config/testdata/similar_rule_keys_bucketing_datafile.json
pkg/config/testdata/similar_rule_keys_bucketing_expected.json
pkg/config/testdata/typed_audience_datafile.json
pkg/entities/audience.go
pkg/entities/experiment.go
pkg/entities/feature.go

The following new public properties are added to OptimizelyConfig:
- sdkKey
- environmentKey
- attributes
- audiences
- events
- experimentRules and deliveryRules to OptimizelyFeature
- audiences to OptimizelyExperiment
All FSC tests OPTIMIZELY_CONFIG_V2 tests should pass.
FSC OptimizelyConfig [link](https://app.travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/236774233) 
https://github.com/optimizely/fullstack-sdk-compatibility-suite/pull/526
Here's the simple snippet when you will run multiple times, it will give you different result. Maps are randomly picked. 
```
package main
import (
"fmt"
)
func main() {
m := map[string]int {
"key1": 1,
"key6": 6,
"key4": 4,
"key3": 3,
"key7": 7,
"key2": 2,					
}
for key, val := range m {
fmt.Println(key)
fmt.Println(val) …
```

feat(OptimizelyConfig): Add new fields to OptimizelyConfig.

---

CHANGELOG.MD
pkg/event/version.go

chore: preparing 1.7.0 release.

---

pkg/client/client.go
pkg/client/optimizely_user_context.go
pkg/client/optimizely_user_context_test.go
pkg/decision/feature_experiment_service.go
pkg/decision/feature_experiment_service_test.go
pkg/decision/forced_decision_service.go
pkg/decision/forced_decision_service_test.go
pkg/decision/rollout_service.go
pkg/decision/rollout_service_test.go

- Updated forced-decision API request parameters.
- Removed empty flag key validation.
- FSC Result: https://app.travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/jobs/544672835

refact(forced-decision): Support for decision context added.

---

pkg/client/optimizely_user_context.go
pkg/client/optimizely_user_context_test.go

- Remove config-ready check from forced-decision apis
- Unit and FSC tests

fix(ForcedDecision): remove config-ready check from forced-decision apis

---

.github/workflows/go.yml
.github/workflows/integration_test.yml

- Fix an issue related to github-action where travis_branch was not set correctlu.
All tests should pass

fix(github-action): fix nits and issues related to github-action

---

pkg/event/factory.go
pkg/event/factory_test.go

- Adds validation on user attributes to only allow primitive types.
- Adds unit tests.
All tests should pass
OASIS-8551

OASIS-8551 fix(attribute-validation): Adds validation on user attributes to only allow primitive types.

---

CHANGELOG.MD
pkg/event/version.go

Prepare for patch release 1.8.1.
- update golang version and changelog
PR with the patch: [PR 339 Adds validation on user attributes to only allow primitive types. ](https://github.com/optimizely/go-sdk/pull/339)
Jira ticket: [OASIS-8563 Release go-sdk (patch release)](https://optimizely.atlassian.net/browse/OASIS-8563)

chore: update version and changelog for patch release

---

CHANGELOG.MD
pkg/event/version.go

Prepare for patch release 1.8.2
- update golang version and changelog
- PR with the patch: https://github.com/optimizely/go-sdk/pull/341
Jira ticket: [OASIS-8593 Release go-sdk (patch release)](https://optimizely.atlassian.net/browse/OASIS-8593)

chore: prepare for patch release 1.8.2

---

pkg/event/dispatcher_test.go
pkg/event/factory.go
pkg/event/factory_test.go

- Fixes issue with visitor where dispatch timestamp was used instead of userEvent creation timestamp.
- FSSDK-8641
- Unit and integration tests should pass.

fix(visitor-timestamp): Fixes issue with visitor timestamp .

---

CHANGELOG.MD
pkg/event/version.go

Prepare for patch release 1.8.3
- update golang version and changelog
- PR with the patch: https://github.com/optimizely/go-sdk/pull/345
- PR with the feature: https://github.com/optimizely/go-sdk/pull/335
Jira ticket: FSSDK-8560

chore: prepare for patch release 1.8.3

---

pkg/odp/lru_cache.go
pkg/odp/lru_cache_test.go

- Added an interface for LRU Caching mechanism.  Include a default implementation.
- Generics were not used since they were introduced in go 1.18 whereas we provide support up-to go 1.12.
Included new tests in the test project
FSSDK-8513

feat: Added a generic LRUCache interface and a default implementation

---

.github/workflows/go.yml
README.md
go.mod
go.sum

- Updating minimum go-sdk version to 1.13
- Updating go-sdk versions for workflows
- All tests should pass

chore: Updating minimum go-sdk version to 1.13

---

pkg/config/polling_manager.go
pkg/event/factory.go
pkg/event/factory_test.go
pkg/odp/audience.go
pkg/odp/config.go
pkg/odp/event.go
pkg/odp/event_api_manager.go
pkg/odp/event_api_manager_test.go
pkg/odp/event_manager.go
pkg/odp/event_manager_test.go
pkg/odp/segment_api_manager.go
pkg/odp/segment_api_manager_test.go
pkg/odp/segment_manager.go
pkg/odp/segment_manager_test.go
pkg/utils/requester.go
pkg/utils/requester_test.go
pkg/utils/types.go
pkg/utils/types_test.go
pkg/utils/utils.go
pkg/utils/utils_test.go

This PR adds support for ODPEventManager. 
- Unit tests added
- FSSDK-8515

feat(event-manager): Adds implementation for ODPEventManager

---

pkg/client/factory.go
pkg/client/optimizely_user_context_odp_test.go
pkg/odp/event/event_manager.go
pkg/odp/event/event_manager_test.go
pkg/odp/odp_manager_test.go

- Removes support for changing odp batchSize. 
- If flush interval is set to 0, flushEvent timer is not started and batchSize is set to 1 to dispatch events immediately .
- Fixes a bug which restricted flushEvent timer to only send events using the odpConfiguration it was initialized with, whereas it should send events using the latest odp configuration.
- Added new unit tests.
- All previous tests should pass.

refact(odp): Removes support for odp batchSize and fixes ticker.

---

pkg/odp/segment/segment_option.go
pkg/odp/segment/segment_option_test.go

segment_option.go has enumerated constants assigning integers to ResetCache and IgnoreCache.
However decide_options.go uses strings.
Changing segments options to also use strings.
This will enable to make work fetch qualified segments in ODP for Agent.
https://jira.sso.episerver.net/browse/FSSDK-8933

Update segments options with strings

---

pkg/client/client.go
pkg/client/client_test.go

Summary
-------
-  Updated SendOdpEvent to require identifiers and contain at least one key
Test plan
---------
- updated client_test.go
Ticket
------
-  [FSSDK-8943](https://jira.sso.episerver.net/browse/FSSDK-8943)

[FSSDK-8943] fix: make odp event identifiers required

---

README.md
docs/readme-sync/sdk-reference-guides/go-sdk/040 - optimizelyconfig-go.md
docs/readme-sync/sdk-reference-guides/go-sdk/070 - event-batching-go.md
pkg/odp/utils/constants.go

Update all non-code-path SDK resources for Feature Experimenation
Jira ticket: https://jira.sso.episerver.net/browse/FSSDK-8957

[FSSDK-8957] Update non-code path resources for FX

---

CHANGELOG.MD
pkg/event/version.go

Bump minor version in changelog to 1.8.4 for renaming of fullstack to feature experimentation
https://jira.sso.episerver.net/browse/FSSDK-8957

[FSSDK-8975] Bump minor version in changelog

---

pkg/odp/segment/segment_api_manager.go
pkg/odp/segment/segment_api_manager_test.go

Support a new format for ODP `InvalidIdentifierException` (when SDK fetches segments with a non-registered userId).
```
"extensions": {
"code": "INVALID_IDENTIFIER_EXCEPTION",
"classification": "DataFetchingException"
}
```
Add unit tests to cover the new response format.
- [FSSDK-9131](https://jira.sso.episerver.net/browse/FSSDK-9131)

[FSSDK-9131] fix for ODP INVALID_IDENTIFIER_EXCEPTION code

---

pkg/config/polling_manager.go
pkg/event/processor.go
pkg/odp/event/event_manager.go

- Fix goroutine leak for ticker
- [FSSDK-9155](https://jira.sso.episerver.net/browse/FSSDK-9155)

[FSSDK-9155] fix(ticker): stop all tickers to prevent goroutine leak

---

pkg/config/polling_manager.go

-  Implements a warning log for polling interval less than 30s
- [FSSDK-9511](https://jira.sso.episerver.net/browse/FSSDK-9511)

 [FSSDK-9511] refact: Implements a warning log for polling interval less than 30s

---

.github/workflows/go.yml
README.md
go.mod

[FSSDK-9591](https://jira.sso.episerver.net/browse/FSSDK-9591)

[FSSDK-9591] chore: bump go version to 1.21.0

---

.github/workflows/source_clear_cron.yml
Makefile
go.mod
pkg/client/client.go
pkg/client/client_test.go
pkg/client/factory.go
pkg/client/factory_test.go
pkg/config/datafileprojectconfig/mappers/condition_trees.go

- Added helper function for notification center needed for https://github.com/optimizely/agent/pull/399
- run source clear check in each PR
- fixed linter error
Ticket: [FSSDK-9632](https://jira.sso.episerver.net/browse/FSSDK-9632)

[FSSDK-9632] Add helper function for notification center

---

CHANGELOG.MD

Ticket: 
- [FSSDK-9698](https://jira.sso.episerver.net/browse/FSSDK-9698)

[FSSDK-9698] chore: prepare for patch release 1.8.5

---

CHANGELOG.MD

- [FSSDK-8584](https://jira.sso.episerver.net/browse/FSSDK-8584)

[FSSDK-8584] bump release data & add module name change info

---

pkg/client/client.go

Ticket:
- [FSSDK-10397](https://jira.sso.episerver.net/browse/FSSDK-10397)

[FSSDK-10397] replace info log with debug log for Decision flow

---

pkg/client/client.go
pkg/client/factory.go
pkg/client/optimizely_user_context.go
pkg/client/optimizely_user_context_test.go
pkg/decision/entities.go
pkg/decision/feature_experiment_service.go
pkg/decision/persisting_experiment_service.go
pkg/decision/rollout_service.go

Ticket: [FSSDK-10764](https://jira.sso.episerver.net/browse/FSSDK-10764)

[FSSDK-10764] add support for batch UPS for decideAll & decideForKeys

---

CHANGELOG.MD
pkg/event/version.go

Ticket: [FSSDK-10845](https://jira.sso.episerver.net/browse/FSSDK-10845)

[FSSDK-10845] chore: prepare for release 2.1.0

---

pkg/config/datafileprojectconfig/config.go
pkg/config/datafileprojectconfig/config_test.go
pkg/config/datafileprojectconfig/entities/entities.go
pkg/config/datafileprojectconfig/mappers/experiment.go
pkg/config/datafileprojectconfig/mappers/experiment_test.go
pkg/entities/experiment.go

User Story
- Update project config to track CMAB properties
Context
- Under the Project Config Update Section of CMAB
Acceptance Criteria
- Complete the update
- Verify testing, add any code coverage as needed
https://jira.sso.episerver.net/browse/FSSDK-11133

[FSSDK-11133] Add cmab to project config

---

pkg/decision/cmab_client.go
pkg/decision/cmab_client_test.go

Add CMAB client and unit tests.
https://jira.sso.episerver.net/browse/FSSDK-11142

[FSSDK-11142] Add cmab client and tests

---

pkg/client/client.go
pkg/client/optimizely_user_context_test.go
pkg/decision/flag_notification.go

- Added `experimentId` and `variationId` to decision notification
- [FSSDK-11451](https://jira.sso.episerver.net/browse/FSSDK-11451)

[FSSDK-11451] Go Implementation: Add Experiment ID + Variation ID to Decision Notification Listener Payload

---

pkg/client/client.go
pkg/client/client_test.go
pkg/cmab/client.go
pkg/cmab/client_test.go
pkg/cmab/service.go
pkg/cmab/service_test.go
pkg/cmab/types.go
pkg/decision/bucketer/experiment_bucketer.go
pkg/decision/composite_experiment_service.go
pkg/decision/composite_experiment_service_test.go
pkg/decision/composite_service_test.go
pkg/decision/entities.go
pkg/decision/evaluator/audience_evaluator.go
pkg/decision/evaluator/audience_evaluator_test.go
pkg/decision/experiment_bucketer_service.go
pkg/decision/experiment_bucketer_service_test.go
pkg/decision/experiment_cmab_service.go
pkg/decision/experiment_cmab_service_test.go
pkg/decision/reasons/reason.go

Decision Service methods to handle CMAB
- added experiment_cmab_service.go file with cmab supportig methods
- additionally updated decision/entities.go and decision/reasons/reason.go
Added unit tests.
Jira ticket: https://jira.sso.episerver.net/browse/FSSDK-11169

[FSSDK-11169] Implement Decision Service methods to handle CMAB

---

pkg/client/client.go
pkg/decision/entities.go
pkg/decision/experiment_cmab_service.go
pkg/decision/experiment_cmab_service_test.go
pkg/decision/feature_experiment_service.go
pkg/decision/feature_experiment_service_test.go
pkg/event/events.go
pkg/event/factory.go
pkg/event/factory_test.go
pkg/event/processor_test.go

- implement logic for cmab impression events
Jira ticket:
https://jira.sso.episerver.net/browse/FSSDK-11178

[FSSDK-11178] Update impression event for CMAB

---

pkg/cmab/service.go
pkg/config/polling_manager_test.go
pkg/odp/cache.go

- remove duplicated retry logic from cmab_service.go, only keep retry in cmab_client
- lru_cache file has been moved to own pkg.cache, that can break cache related to odp code, creating a cache wrapper such that all new code uses the new location in pkg/cache/cache.go and old odp code will stil be compatible and work with the old cache location.
- added deprecation comment to the wrapper
All unit tests pass, unchanged.
Jira: https://jira.sso.episerver.net/browse/FSSDK-11635

[FSSDK-11635] remove duplicated fetch method, add cache wrapper
