optimizely/go-sdk

- optimizely/client/client.go
- optimizely/client/client_test.go
- optimizely/config/datafileprojectconfig/config.go
- optimizely/interface.go
- Add `GetEnabledFeatures` as a function in `client.go`
- Add `GetFeatureList()` function in `datafileprojectconfig/config.go`
- Unit tests in `client_test.go`
- `TestGetEnabledFeatures` checks that the function returns 1 out of 2 features
- `TestGetEnabledFeaturesErrorCases` checks for error upon invalid Optimizely instance
- `TestGetEnabledFeaturesPanic` tests for panic and recovery in the function
[OASIS-5107](https://optimizely.atlassian.net/browse/OASIS-5107)
> feat(getenabledfeatures): Add GetEnabledFeatures API

- CHANGELOG.MD
- Adding changelog for visibility
> chore: Add changelog for rollouts beta.

- README.md
- Adds a note on us doing trunk-based dev and one way to pin versions
> chore(readme): Add instructions for version pinning.

- optimizely/config/datafileprojectconfig/config.go
- optimizely/config/datafileprojectconfig/config_test.go
This adds unit tests for all of the config getters.
> Add unit tests for datafile project config.

- optimizely/decision/composite_feature_service.go
- optimizely/decision/feature_experiment_service.go
This is in preparation for adding mutex support.
> Moving experiment evaluation from CompositeFeatureService to FeatureExperimentService

- optimizely/client/client.go
one comment:  I tried to put that recovery logic in a common function and that did not work. For some reason recovery did not initiate from outside the calling function.
> handling recovery errors more elegantly

- optimizely/config/polling_manager.go
- optimizely/config/polling_manager_test.go
1. Added datafile revision updated log in datafile polling manager.
> Added info log for datafile revision update.

- optimizely/config/polling_manager.go
1. Added log for the scenario when datafile is initially assigned according to current `java` implementation.
> fix(datafile-log): Log added for initial datafile assignment.

- .travis.yml
- README.md
- Added unit tests as part of stage
- changed badge link pointing to go-alpha, now pointing to master
> refact(ci): Refactored travis.yml file and introduced stages for unit test

- CHANGELOG.MD
- README.md
- Adds breaking changes to the CHANGELOG
- Updates installation path in the README
> chore: Update changelog and readme with latest changes.

- CHANGELOG.MD
- pkg/version.go
- Bumps version and updates changelog entry
> chore: Prepare 1.0.0-beta3 relesae.

- tests/integration/support/steps.go
- tests/integration/support/utils.go
- Added support for dispatched events comparison. Verified dispatched event tests for `is_feature_enabled/feature_experiments/audience_targeting.feature`.
> refac(gherkins): Fixed comparison of dispatched events.

- pkg/event/factory.go
- tests/integration/main_test.go
- tests/integration/models/constants.go
- tests/integration/models/get_variation_params.go
- tests/integration/optlyplugins/test_composite_service.go
- tests/integration/support/client_wrapper.go
- tests/integration/support/steps.go
- tests/integration/support/utils.go
- Added steps for testing dispatched events of is_feature_enabled api.
- Added steps to process activate and getVariation API's.
- Added support for testing feature-variable api listener's.
> feat(gherkin): Added new steps and support for testing activate, get_variation API's and feature-variable api listeners.

- CHANGELOG.MD
- README.md
- pkg/version.go
> chore: Prepare 1.0.0-beta4 release.

- tests/integration/support/steps.go
- Bypassing listener-called tests for now.
> refact(gherkin):Bypass listener-called tests.

- tests/integration/main_test.go
- tests/integration/models/api_options.go
- tests/integration/models/constants.go
- tests/integration/models/get_feature_variable_params.go
- tests/integration/models/is_feature_enabled_params.go
- tests/integration/models/track_params.go
- tests/integration/optlyplugins/proxy_dispatcher.go
- tests/integration/optlyplugins/test_composite_service.go
- tests/integration/support/client_wrapper.go
- tests/integration/support/steps.go
- Added steps to process track API.
- General fixes.
> feat(gherkin-track): Added new steps and support for testing track API.

- pkg/config/datafileprojectconfig/mappers/condition_trees.go
- pkg/config/datafileprojectconfig/mappers/condition_trees_test.go
- Added support for parsing map for leaf condition.
- Made further methods from `buildConditionTree` method to avoid cyclo-complexity warnings from linter.
> feat(audience-evaluation): Added support for parsing map for leaf condition.

- scripts/run-fsc-tests.sh
- tests/integration/support/client_wrapper.go
- Added close call after invoke API
- Added -f flag to reduce verbosity.
> fix(fsc): Added close call after invoke api

- CHANGELOG.MD
- README.md
- pkg/version.go
- Bumped version and added changelog entries
- Updated the README to reflect simplified init
> chore: Prep 1.0.0-rc1 release.

- .travis.yml
- Integrated with FSC
- Removed Local gherkin
- It should pass FSC
> ci: Run FSC tests

- CONTRIBUTING.md
- pkg/config/optimizely_config.go
Add a CONTRIBUTING.md file with basic instructions for contributors to Go SDK.
> chore: Add CONTRIBUTING.md

- CHANGELOG.MD
- pkg/event/version.go
- Add Changelog entries
- Bumps version number
> chore: Prepare 1.1.0 release

- .travis.yml
- go.mod
- go.sum
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/entities/feature.go
- pkg/optimizelyjson/optimizely_json.go
- pkg/optimizelyjson/optimizely_json_test.go
- renamed GetAllFeatureVariables to GetAllFeatureVariablesWithDecision - still needed for Agent
- fixed error handling in GetAllFeatureVariablesWithDecision
- added 2 public API's GetFeatureVariableJSON and GetAllFeatureVariables
> feat: added GetFeatureVariableJSON and GetAllFeatureVariables

- CHANGELOG.MD
- pkg/event/version.go
in separate pr we have fix not yet merged.
> chore (release): prepare for 1.1.3 release

- docs/010 - install-sdk-go.md
- docs/020 - initialize-sdk-go.md
- docs/030 - example-usage-go.md
- docs/040 - optimizelyconfig-go.md
- docs/050 - implement-a-user-profile-service-go.md
- docs/060 - configure-event-dispatcher-go.md
- docs/070 - event-batching-go.md
- docs/080 - customize-logger-go.md
- docs/090 - customize-error-handler-go.md
- docs/100 - pass-in-audience-attributes-go.md
- docs/110 - set-up-notification-listener-go.md
- docs/120 - activate-go.md
- docs/130 - get-enabled-features-go.md
- docs/140 - get-feature-variable-go.md
- docs/150 - get-forced-variation-go.md
- docs/160 - get-variation-go.md
- docs/170 - is-feature-enabled-go.md
- docs/180 - set-forced-variation-go.md
- docs/181 - remove-forced-variation-go.md
- docs/190 - track-go.md
- docs/index.md
> adding SDK guides for readme.io

- CHANGELOG.MD
- pkg/event/version.go
> chore: prepare for 3.4 release

- CHANGELOG.MD
- pkg/event/version.go
> chore: preparing 1.5.0 release

- CHANGELOG.MD
- pkg/event/version.go
> chore: making 1.5.1 release

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/factory.go
- pkg/client/factory_test.go
- pkg/client/optimizely_decision.go
- pkg/client/optimizely_decision_test.go
- pkg/client/optimizely_user_context.go
- pkg/client/optimizely_user_context_test.go
- pkg/decide/decide_errors.go
- pkg/decide/decide_options.go
A part of multiple PRs for Decide API
- added OptimizelyUserContext
- added setUserContext API
- Unit tests added.
> feat(decide): add UserContext.

- pkg/client/client.go
- pkg/client/optimizely_decision.go
- pkg/client/optimizely_decision_test.go
- pkg/client/optimizely_user_context.go
- pkg/client/optimizely_user_context_test.go
Changes needed for agent - making OptimizelyDecision and OptimizelyUserContext fields public.
> refact: Changes needed for agent

- pkg/client/optimizely_user_context.go
> fix: small changes for agent

- pkg/client/optimizely_user_context.go
1. Small json changes for agent.
> fix(userContext): fixing userContext json keys for agent.

- CHANGELOG.MD
- pkg/event/version.go
Updated CHANGELOG and version files.
> chore: preparing 1.6.0 release

- pkg/client/optimizely_decision.go
- pkg/client/optimizely_decision_test.go
- pkg/decide/decide_errors.go
- Added fixes for decide reasons and variables.
- Updated unit tests.
- FSC PR 495 Result: https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/218330567
> fix(decide-reasons): fixes issues for decision variables and reasons.

- CHANGELOG.MD
- pkg/event/version.go
> chore: prepare 1.6.1 release

- CHANGELOG.MD
- pkg/event/version.go
> chore: prepare for release 1.8.0

- .github/workflows/go.yml
- .github/workflows/integration_test.yml
- Git actions updated to run FSC on git actions.
- Need to change travisci-tools branch from `mnoman/gitActions` to `master`
> feat: updated for fsc git action

- .github/workflows/go.yml
> fix: fixed branch issue.

- pkg/client/client.go
- pkg/client/client_test.go
Summary
-------
Adds valid project config check to sendOdpEvent.
Test plan
---------
- All tests should pass.
Ticket
------
[FSSDK-9087](https://jira.sso.episerver.net/browse/FSSDK-9087)
> [FSSDK-9087]: Adds valid project config check to sendOdpEvent.

- CHANGELOG.MD
- README.md
- pkg/event/version.go
- pkg/odp/event/event_api_manager.go
- pkg/odp/event/event_api_manager_test.go
- Preparing for 2.0.0-beta pre release
- [FSSDK-9109](https://jira.sso.episerver.net/browse/FSSDK-9109)
> [FSSDK-9109]chore: prepare for pre release 2.0.0-beta

- examples/main.go
- Updating example code and sdkKey to use decide.
- [FSSDK-8991](https://jira.sso.episerver.net/browse/FSSDK-8991)
> [FSSDK-8991]refact: Updating example code and sdkKey to use decide.

- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/ENHANCEMENT.yml
- .github/ISSUE_TEMPLATE/FEATURE-REQUEST.md
- .github/ISSUE_TEMPLATE/config.yml
Ticket: [FSSDK-9550](https://jira.sso.episerver.net/browse/FSSDK-9550)
> [FSSDK-9550] chore: add github issue template
